spring:
  application:
    name: _01_LoginForm
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: sh
    password: sh
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /app
logging:
  level:
    root: info
    com.sh: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.sh
  mapper-locations: classpath*:mappers/**/*-mapper.xml